12

diff --git a/DAST.yml b/DAST.yml
--- a/DAST.yml
+++ b/DAST.yml
@@ -27,10 +27,12 @@ phases:
       - echo "=== Checking ZAP is reachable ==="
       - curl -s "$ZAP_URL/JSON/core/view/version/?apikey=$ZAP_API_KEY"
       - echo "=== Checking TARGET_URL is reachable from CodeBuild ==="
-      - curl -I $TARGET_URL || { echo "ERROR: Target not reachable"; exit 1; }
+      - |
+        curl -I $TARGET_URL || { echo "ERROR: Target not reachable"; exit 1; }
       - echo "=== Encoding URL ==="
       - ENCODED_TARGET=$(printf %s "$TARGET_URL" | jq -sRr @uri)
-      - echo "Encoded Target: $ENCODED_TARGET"
+      - |
+        echo "Encoded Target: $ENCODED_TARGET"
 
   build:
     commands:
@@ -39,7 +41,8 @@ phases:
         SPIDER_SCAN_ID=$(curl -s \
         "$ZAP_URL/JSON/spider/action/scan/?apikey=$ZAP_API_KEY&url=$ENCODED_TARGET&recurse=true&subtreeOnly=false" \
         | jq -r '.scan')
-      - echo "Spider scan id: $SPIDER_SCAN_ID"
+      - |
+        echo "Spider scan id: $SPIDER_SCAN_ID"
 
       - |
         STATUS=0
@@ -57,7 +60,8 @@ phases:
         ASCAN_ID=$(curl -s \
         "$ZAP_URL/JSON/ascan/action/scan/?apikey=$ZAP_API_KEY&url=$ENCODED_TARGET&recurse=true&inScopeOnly=false" \
         | jq -r '.scan')
-      - echo "Active scan id: $ASCAN_ID"
+      - |
+        echo "Active scan id: $ASCAN_ID"
 
       - |
         ASTATUS=0
@@ -86,7 +90,8 @@ phases:
       - >
         HIGH_COUNT=$(jq '[.site[].alerts[] | select(.riskcode=="3")] | length' \
         dast-report/zap_report.json)
-      - echo "High alerts found: $HIGH_COUNT"
+      - |
+        echo "High alerts found: $HIGH_COUNT"
 
       - |
         if [ "$HIGH_COUNT" -gt 0 ]; then
